### ISSUE TITLE
《Modify》の辞書ファイルを既存の.txtに加えて.csvにも対応し、空白文字を含むパターンへの対応性を向上します

### ISSUE THREAD

**Issue by usagi** [usagi/virtual-avatar-connect#45]
## 提案

《Modify》の辞書ファイルを既存の.txtに加えて.csvにも対応し、空白文字を含むパターンへの対応性を向上します

## 背景

現在は.txtから空白文字で置換基と置換先を区別しています。この方式は簡潔なパターンについては記述が楽という利点があります。しかし、空白文字を含むパターンを使えないことが不便となる場合もあります。例えば !bsr コマンドの応答を簡素化したい場合など。

## 使い方

《Modify》の設定で regex_files に従来から対応している .txt ファイルと同様に .csv ファイルを指定するだけで使用できます。

### 設定例

↓conf.toml

```toml
# chat チャンネルへの入力を
# regex.chat.csv で定義された正規表現で置換して
# chat-synth チャンネルへ出力する設定例です。
[[processors]]
feature = "modify"
channel_from = "chat"
channel_to = "chat-synth"
regex_files = ["regex.chat.csv"]
```

↓regex.chat.csv

```csv
パチパチパチ,"[8８]{3,}"
パチパチ,".*ﾊﾟﾁﾊﾟﾁ.*"
$1 (以下略),"^(.{32}).*"
```

1. 拍手っぽい表現を「パチパチ」に正規化、ぱたーん１
2. 拍手っぽい表現を「パチパチ」に正規化、ぱたーん２
3. 32文字を超える入力があったら「32文字目まで (以下略)」にするぱたーん
